"""Report rendering: JSON and HackerOne-style markdown (h1md)."""

from __future__ import annotations

import json

from ouija.models import ScanResult, Severity

# Bug-bounty business-impact framing per category.
_IMPACT = {
    "prompt_injection": (
        "An attacker can override the application's system instructions, "
        "causing the LLM to ignore its guardrails. Depending on the app's "
        "capabilities this enables unauthorized actions, content-policy "
        "bypass, data exfiltration via downstream tools, and reputational harm."
    ),
    "sensitive_info_disclosure": (
        "The endpoint leaks information it should keep confidential (system "
        "prompts, configuration, credentials, or PII). This aids further "
        "attacks and may itself be a privacy/compliance violation."
    ),
    "model_dos": (
        "The endpoint can be coerced into unbounded generation, driving up "
        "latency and cost (token-based billing) and degrading availability "
        "for legitimate users."
    ),
    "improper_output_handling": (
        "The endpoint renders attacker-controlled markup (markdown images, "
        "links, or HTML) into its output. When that output is auto-rendered by "
        "a downstream surface, the embedded URL is fetched silently — "
        "exfiltrating system prompts, conversation history, or secrets to an "
        "attacker-controlled host with zero user interaction (EchoLeak / "
        "CVE-2025-32711 'lethal trifecta' class)."
    ),
}

_SEVERITY_ORDER = {
    Severity.CRITICAL: 0,
    Severity.HIGH: 1,
    Severity.MEDIUM: 2,
    Severity.LOW: 3,
    Severity.INFO: 4,
}


def to_json(result: ScanResult) -> str:
    return json.dumps(result.model_dump(mode="json"), indent=2)


def to_h1md(result: ScanResult) -> str:
    findings = sorted(
        result.findings, key=lambda f: _SEVERITY_ORDER.get(f.severity, 99)
    )
    lines: list[str] = []
    lines.append(f"# ouija findings report — {result.target}")
    lines.append("")
    lines.append(
        f"_Generated by ouija v{result.version}. Attack set: `{result.attack_set}`. "
        f"{result.patterns_sent} attack requests sent. "
        f"{len(findings)} finding(s)._"
    )
    lines.append("")

    if not findings:
        lines.append("No findings. The target refused or sanitized all probes "
                     "in this attack set.")
        lines.append("")
        return "\n".join(lines)

    for idx, f in enumerate(findings, start=1):
        lines.append(f"## Finding {idx}: {f.title}")
        lines.append("")
        lines.append(f"**Severity:** {f.severity.value.upper()}  ")
        lines.append(f"**Category:** {f.category}  ")
        lines.append(f"**OWASP LLM Top 10:** {f.owasp}  ")
        lines.append(f"**Confidence:** {f.confidence:.0%}  ")
        if f.attempts > 1:
            lines.append(
                f"**Reliability:** {f.successes}/{f.attempts} attempts "
                f"({f.success_rate:.0%})  "
            )
        lines.append(f"**Finding ID:** `{f.id}`  ")
        lines.append(f"**Pattern:** `{f.pattern_id}` (technique: {f.technique})")
        lines.append("")
        lines.append("### Summary")
        lines.append(f.evidence)
        lines.append("")
        lines.append("### Steps to reproduce")
        lines.append("")
        lines.append(f"1. Send the following prompt to `{result.target}`:")
        lines.append("")
        lines.append("```")
        lines.append(f.request_prompt)
        lines.append("```")
        lines.append("")
        lines.append("2. Observe the response, which contained:")
        lines.append("")
        lines.append("```")
        lines.append(f.response_excerpt)
        lines.append("```")
        lines.append("")
        lines.append("### Business impact")
        lines.append(_IMPACT.get(f.category, "See category description."))
        lines.append("")
        lines.append("---")
        lines.append("")

    return "\n".join(lines)


def render(result: ScanResult, fmt: str) -> str:
    if fmt == "json":
        return to_json(result)
    if fmt == "h1md":
        return to_h1md(result)
    raise ValueError(f"unknown format '{fmt}'")
